var codCiiu = new Map();
var ciiu1 = document.getElementById("codCiiu1");
var ciiu2 = document.getElementById("codCiiu2");
//var fullDir = document.getElementById("fullDir");
//var dirResidencia = document.getElementById("dirResidencia");

fill();
validateCIIU(ciiu1,"ciiu1");
validateCIIU(ciiu2,"ciiu2");


function direccion(select, input, dir){
    var fullDir = document.getElementById(dir);
    fullDir.innerHTML = "";    
    for(var i=1; i<=5; i++){
        document.getElementById(input+i).value = document.getElementById(input+i).value.split(/[`~!@#$%^&*()_|+\-¿¡=?°¬;:'",.<>\{\}\[\]\\\/]/gi).join(""); 
        fullDir.innerHTML += document.getElementById(select+i).value + " " + document.getElementById(input+i).value.toString().toUpperCase() + " ";        //.replace("-"," ")
    }        
}

function guardarDir( cancel, fullD, dir){
    var fullDir = document.getElementById(fullD);
    var dirResidencia = document.getElementById(dir);
    dirResidencia.value = fullDir.innerHTML;
    document.getElementById(cancel).click();
}



function validateCIIU(element,ciiu){
    if(element.value != ""){
        var description = codCiiu.get(element.value.toString());
        console.log(description);
        if(description != undefined){
            console.log("aca"+element.value);
            document.getElementById(ciiu).value=description;                        
        }else{
            document.getElementById(ciiu).value="";            
        }
    }else{
        document.getElementById(ciiu).value="";        
    }
}


function validateErase(element,ciiu){
    if(element.value == ""){
        document.getElementById(ciiu).value="";     
    }
}

function validateArrowKey(e){
    var n = (window.Event) ? e.which : e.keyCode;
    if (n==38 || n==40){        
        return false;
    } 
}


function fill(){
    codCiiu.set('111','Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas');
    codCiiu.set('112','Cultivo de arroz ');
    codCiiu.set('113','Cultivo de hortalizas, raíces y tubérculos ');
    codCiiu.set('114','Cultivo de tabaco ');
    codCiiu.set('115','Cultivo de plantas textiles ');
    codCiiu.set('119','Otros cultivos transitorios n.c.p.');
    codCiiu.set('121','Cultivo de frutas tropicales y subtropicales');
    codCiiu.set('122','Cultivo de plátano y banano');
    codCiiu.set('123','Cultivo de café');
    codCiiu.set('124','Cultivo de caña de azúcar');
    codCiiu.set('125','Cultivo de flor de corte');
    codCiiu.set('126','Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos');
    codCiiu.set('127','Cultivo de plantas con las que se preparan bebidas');
    codCiiu.set('128','Cultivo de especias y de plantas aromáticas y medicinales ');
    codCiiu.set('129','Otros cultivos permanentes n.c.p.');
    codCiiu.set('130','Propagación de plantas (actividades de los viveros, excepto viveros forestales) ');
    codCiiu.set('141','Cría de ganado bovino y bufalino');
    codCiiu.set('142','Cría de caballos y otros equinos ');
    codCiiu.set('143','Cría de ovejas y cabras ');
    codCiiu.set('144','Cría de ganado porcino');
    codCiiu.set('145','Cría de aves de corral');
    codCiiu.set('149','Cría de otros animales n.c.p.');
    codCiiu.set('150','Explotación mixta (agrícola y pecuaria) ');
    codCiiu.set('161','Actividades de apoyo a la agricultura ');
    codCiiu.set('162','Actividades de apoyo a la ganadería');
    codCiiu.set('163','Actividades posteriores a la cosecha ');
    codCiiu.set('164','Tratamiento de semillas para propagación ');
    codCiiu.set('170','Caza ordinaria y mediante trampas y actividades de servicios conexas ');
    codCiiu.set('210','Silvicultura y otras actividades forestales');
    codCiiu.set('220','Extracción de madera ');
    codCiiu.set('230','Recolección de productos forestales diferentes a la madera');
    codCiiu.set('240','Servicios de apoyo a la silvicultura ');
    codCiiu.set('311','Pesca marítima ');
    codCiiu.set('312','Pesca de agua dulce ');
    codCiiu.set('321','Acuicultura marítima ');
    codCiiu.set('322','Acuicultura de agua dulce');
    codCiiu.set('510','Extracción de hulla (carbón de piedra)');
    codCiiu.set('520','Extracción de carbón lignito');
    codCiiu.set('610','Extracción de petróleo crudo');
    codCiiu.set('620','Extracción de gas natural');
    codCiiu.set('710','Extracción de minerales de hierro');
    codCiiu.set('721','Extracción de minerales de uranio y de torio');
    codCiiu.set('722','Extracción de oro y otros metales preciosos');
    codCiiu.set('723','Extracción de minerales de níquel');
    codCiiu.set('729','Extracción de otros minerales metalíferos no ferrosos n.c.p.');
    codCiiu.set('811','Extracción de piedra, arena, arcillas comunes, yeso y anhidrita');
    codCiiu.set('812','Extracción de arcillas de uso industrial, caliza, caolón y bentonitas');
    codCiiu.set('820','Extracción de esmeraldas, piedras preciosas y semipreciosas');
    codCiiu.set('891','Extracción de minerales para la fabricación de abonos y productos químicos');
    codCiiu.set('892','Extracción de halita (sal)');
    codCiiu.set('899','Extracción de otros minerales no metálicos n.c.p.');
    codCiiu.set('910','Actividades de apoyo para la extracción de petróleo y de gas natural');
    codCiiu.set('990','Actividades de apoyo para otras actividades de explotación de minas y canteras');
    codCiiu.set('1011','Procesamiento y conservación de carne y productos cárnicos');
    codCiiu.set('1012','Procesamiento y conservación de pescados, crustáceos y moluscos');
    codCiiu.set('1020','Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos');
    codCiiu.set('1030','Elaboración de aceites y grasas de origen vegetal y animal');
    codCiiu.set('1040','Elaboración de productos lacteos');
    codCiiu.set('1051','Elaboración de productos de molinería');
    codCiiu.set('1052','Elaboración de almidones y productos derivados del almidón');
    codCiiu.set('1061','Trilla de café');
    codCiiu.set('1062','Descafeinado, tostión y molienda del café');
    codCiiu.set('1063','Otros derivados del café');
    codCiiu.set('1071','Elaboración y refinación de azúcar');
    codCiiu.set('1072','Elaboración de panela');
    codCiiu.set('1081','Elaboración de productos de panadería');
    codCiiu.set('1082','Elaboración de cacao, chocolate y productos de confitería');
    codCiiu.set('1083','Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares');
    codCiiu.set('1084','Elaboración de comidas y platos preparados');
    codCiiu.set('1089','Elaboración de otros productos alimenticios n.c.p.');
    codCiiu.set('1090','Elaboración de alimentos preparados para animales');
    codCiiu.set('1101','Destilación, rectificación y mezcla de bebidas alcohólicas');
    codCiiu.set('1102','Elaboración de bebidas fermentadas no destiladas');
    codCiiu.set('1103','Producción de malta, elaboración de cervezas y otras bebidas malteadas');
    codCiiu.set('1104','Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas');
    codCiiu.set('1200','Elaboración de productos de tabaco');
    codCiiu.set('1311','Preparación e hilatura de fibras textiles');
    codCiiu.set('1312','Tejeduría de productos textiles');
    codCiiu.set('1313','Acabado de productos textiles');
    codCiiu.set('1391','Fabricación de tejidos de punto y ganchillo');
    codCiiu.set('1392','Confección de artículos con materiales textiles, excepto prendas de vestir');
    codCiiu.set('1393','Fabricación de tapetes y alfombras para pisos');
    codCiiu.set('1394','Fabricación de cuerdas, cordeles, cables, bramantes y redes');
    codCiiu.set('1399','Fabricación de otros artículos textiles n.c.p.');
    codCiiu.set('1410','Confección de prendas de vestir, excepto prendas de piel');
    codCiiu.set('1420','Fabricación de artículos de piel');
    codCiiu.set('1430','Fabricación de artículos de punto y ganchillo');
    codCiiu.set('1511','"Curtido y recurtido de cueros; recurtido y teñido de pieles    ');
    codCiiu.set('1512','Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería');
    codCiiu.set('1513','"Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales"');
    codCiiu.set('1521','Fabricación de calzado de cuero y piel, con cualquier tipo de suela');
    codCiiu.set('1522','Fabricación de otros tipos de calzado, excepto calzado de cuero y piel');
    codCiiu.set('1523','Fabricación de partes del calzado');
    codCiiu.set('1610','Aserrado, acepillado e impregnación de la madera');
    codCiiu.set('1620','"Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles"');
    codCiiu.set('1630','Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción');
    codCiiu.set('1640','Fabricación de recipientes de madera');
    codCiiu.set('1690','"Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería"');
    codCiiu.set('1701','"Fabricación de pulpas (pastas) celulásicas; papel y cartón"');
    codCiiu.set('1702','"Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón."');
    codCiiu.set('1709','Fabricación de otros artículos de papel y cartón');
    codCiiu.set('1811','Actividades de impresión');
    codCiiu.set('1812','Actividades de servicios relacionados con la impresión');
    codCiiu.set('1820','Producción de copias a partir de grabaciones originales ');
    codCiiu.set('1910','Fabricación de productos de hornos de coque');
    codCiiu.set('1921','Fabricación de productos de la refinación del petróleo');
    codCiiu.set('1922','Actividad de mezcla de combustibles');
    codCiiu.set('2011','Fabricación de sustancias y productos químicos básicos');
    codCiiu.set('2012','Fabricación de abonos y compuestos inorgánicos nitrogenados');
    codCiiu.set('2013','Fabricación de plásticos en formas primarias');
    codCiiu.set('2014','Fabricación de caucho sintótico en formas primarias');
    codCiiu.set('2021','Fabricación de plaguicidas y otros productos químicos de uso agropecuario');
    codCiiu.set('2022','Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas');
    codCiiu.set('2023','"Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador"');
    codCiiu.set('2029','Fabricación de otros productos químicos n.c.p.');
    codCiiu.set('2030','Fabricación de fibras sintéticas y artificiales');
    codCiiu.set('2100','Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico');
    codCiiu.set('2211','Fabricación de llantas y neumáticos de caucho');
    codCiiu.set('2212','Reencauche de llantas usadas');
    codCiiu.set('2219','Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.');
    codCiiu.set('2221','Fabricación de formas básicas de plástico');
    codCiiu.set('2229','Fabricación de artículos de plástico n.c.p.');
    codCiiu.set('2310','Fabricación de vidrio y productos de vidrio');
    codCiiu.set('2391','Fabricación de productos refractarios');
    codCiiu.set('2392','Fabricación de materiales de arcilla para la construcción');
    codCiiu.set('2393','Fabricación de otros productos de cerámica y porcelana');
    codCiiu.set('2394','Fabricación de cemento, cal y yeso');
    codCiiu.set('2395','Fabricación de artículos de hormigón, cemento y yeso');
    codCiiu.set('2396','Corte, tallado y acabado de la piedra');
    codCiiu.set('2399','Fabricación de otros productos minerales no metálicos n.c.p.');
    codCiiu.set('2410','Industrias básicas de hierro y de acero');
    codCiiu.set('2421','Industrias básicas de metales preciosos');
    codCiiu.set('2429','Industrias básicas de otros metales no ferrosos');
    codCiiu.set('2431','Fundición de hierro y de acero');
    codCiiu.set('2432','Fundición de metales no ferrosos ');
    codCiiu.set('2511','Fabricación de productos metálicos para uso estructural');
    codCiiu.set('2512','Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías');
    codCiiu.set('2513','Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central');
    codCiiu.set('2520','Fabricación de armas y municiones');
    codCiiu.set('2591','"Forja, prensado, estampado y laminado de metal; pulvimetalurgia"');
    codCiiu.set('2592','"Tratamiento y revestimiento de metales; mecanizado"');
    codCiiu.set('2593','Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería');
    codCiiu.set('2599','Fabricación de otros productos elaborados de metal n.c.p.');
    codCiiu.set('2610','Fabricación de componentes y tableros electrónicos');
    codCiiu.set('2620','Fabricación de computadoras y de equipo periférico');
    codCiiu.set('2630','Fabricación de equipos de comunicación');
    codCiiu.set('2640','Fabricación de aparatos electrónicos de consumo');
    codCiiu.set('2651','Fabricación de equipo de medición, prueba, navegación y control');
    codCiiu.set('2652','Fabricación de relojes');
    codCiiu.set('2660','Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico');
    codCiiu.set('2670','Fabricación de instrumentos ópticos y equipo fotográfico');
    codCiiu.set('2680','Fabricación de medios magnéticos y ópticos para almacenamiento de datos');
    codCiiu.set('2711','Fabricación de motores, generadores y transformadores eléctricos');
    codCiiu.set('2712','Fabricación de aparatos de distribución y control de la energía eléctrica');
    codCiiu.set('2720','Fabricación de pilas, baterías y acumuladores eléctricos');
    codCiiu.set('2731','Fabricación de hilos y cables eléctricos y de fibra óptica');
    codCiiu.set('2732','Fabricación de dispositivos de cableado');
    codCiiu.set('2740','Fabricación de equipos eléctricos de iluminación');
    codCiiu.set('2750','Fabricación de aparatos de uso doméstico');
    codCiiu.set('2790','Fabricación de otros tipos de equipo eléctrico n.c.p.');
    codCiiu.set('2811','Fabricación de motores, turbinas, y partes para motores de combustión interna');
    codCiiu.set('2812','Fabricación de equipos de potencia hidráulica y neumática');
    codCiiu.set('2813','Fabricación de otras bombas, compresores, grifos y válvulas');
    codCiiu.set('2814','Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión');
    codCiiu.set('2815','Fabricación de hornos, hogares y quemadores industriales');
    codCiiu.set('2816','Fabricación de equipo de elevación y manipulación');
    codCiiu.set('2817','Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)');
    codCiiu.set('2818','Fabricación de herramientas manuales con motor');
    codCiiu.set('2819','Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.');
    codCiiu.set('2821','Fabricación de maquinaria agropecuaria y forestal');
    codCiiu.set('2822','Fabricación de máquinas formadoras de metal y de máquinas herramienta');
    codCiiu.set('2823','Fabricación de maquinaria para la metalurgia');
    codCiiu.set('2824','Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción');
    codCiiu.set('2825','Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco');
    codCiiu.set('2826','Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros');
    codCiiu.set('2829','Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.');
    codCiiu.set('2910','Fabricación de vehículos automotores y sus motores');
    codCiiu.set('2920','"Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques "');
    codCiiu.set('2930','Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores');
    codCiiu.set('3011','Construcción de barcos y de estructuras flotantes');
    codCiiu.set('3012','Construcción de embarcaciones de recreo y deporte');
    codCiiu.set('3020','Fabricación de locomotoras y de material rodante para ferrocarriles');
    codCiiu.set('3030','Fabricación de aeronaves, naves espaciales y de maquinaria conexa');
    codCiiu.set('3040','Fabricación de vehículos militares de combate');
    codCiiu.set('3091','Fabricación de motocicletas');
    codCiiu.set('3092','Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad');
    codCiiu.set('3099','Fabricación de otros tipos de equipo de transporte n.c.p.');
    codCiiu.set('3110','Fabricación de muebles ');
    codCiiu.set('3120','Fabricación de colchones y somieres');
    codCiiu.set('3210','Fabricación de joyas, bisutería y artículos conexos');
    codCiiu.set('3220','Fabricación de instrumentos musicales');
    codCiiu.set('3230','Fabricación de artículos y equipo para la práctica del deporte');
    codCiiu.set('3240','Fabricación de juegos, juguetes y rompecabezas');
    codCiiu.set('3250','Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)');
    codCiiu.set('3290','Otras industrias manufactureras n.c.p.');
    codCiiu.set('3311','Mantenimiento y reparación especializado de productos elaborados en metal');
    codCiiu.set('3312','Mantenimiento y reparación especializado de maquinaria y equipo');
    codCiiu.set('3313','Mantenimiento y reparación especializado de equipo electrónico y óptico');
    codCiiu.set('3314','Mantenimiento y reparación especializado de equipo elóctrico');
    codCiiu.set('3315','Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas');
    codCiiu.set('3319','Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.');
    codCiiu.set('3320','Instalación especializada de maquinaria y equipo industrial ');
    codCiiu.set('3511','Generación de energía eléctrica');
    codCiiu.set('3512','Transmisión de energía eléctrica');
    codCiiu.set('3513','Distribución de energía eléctrica');
    codCiiu.set('3514','Comercialización de energía eléctrica');
    codCiiu.set('3520','"Producción de gas; distribución de combustibles gaseosos por tuberías"');
    codCiiu.set('3530','Suministro de vapor y aire acondicionado');
    codCiiu.set('3600','Captación, tratamiento y distribución de agua');
    codCiiu.set('3700','Evacuación y tratamiento de aguas residuales');
    codCiiu.set('3811','Recolección de desechos no peligrosos');
    codCiiu.set('3812','Recolección de desechos peligrosos');
    codCiiu.set('3821','Tratamiento y disposición de desechos no peligrosos');
    codCiiu.set('3822','Tratamiento y disposición de desechos peligrosos');
    codCiiu.set('3830','Recuperación de materiales');
    codCiiu.set('3900','Actividades de saneamiento ambiental y otros servicios de gestión de desechos');
    codCiiu.set('4111','Construcción de edificios residenciales');
    codCiiu.set('4112','Construcción de edificios no residenciales');
    codCiiu.set('4210','Construcción de carreteras y vías de ferrocarril');
    codCiiu.set('4220','Construcción de proyectos de servicio público');
    codCiiu.set('4290','Construcción de otras obras de ingeniería civil');
    codCiiu.set('4311','Demolición');
    codCiiu.set('4312','Preparación del terreno');
    codCiiu.set('4321','Instalaciones eléctricas');
    codCiiu.set('4322','Instalaciones de fontanería, calefacción y aire acondicionado');
    codCiiu.set('4329','Otras instalaciones especializadas');
    codCiiu.set('4330','Terminación y acabado de edificios y obras de ingeniería civil');
    codCiiu.set('4390','Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil');
    codCiiu.set('4511','Comercio de vehículos automotores nuevos');
    codCiiu.set('4512','Comercio de vehículos automotores usados');
    codCiiu.set('4520','Mantenimiento y reparación de vehículos automotores');
    codCiiu.set('4530','Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores');
    codCiiu.set('4541','Comercio de motocicletas y de sus partes, piezas y accesorios');
    codCiiu.set('4542','Mantenimiento y reparación de motocicletas y de sus partes y piezas');
    codCiiu.set('4610','Comercio al por mayor a cambio de una retribución o por contrata');
    codCiiu.set('4620','"Comercio al por mayor de materias primas agropecuarias; animales vivos"');
    codCiiu.set('4631','Comercio al por mayor de productos alimenticios');
    codCiiu.set('4632','Comercio al por mayor de bebidas y tabaco');
    codCiiu.set('4641','Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico');
    codCiiu.set('4642','Comercio al por mayor de prendas de vestir');
    codCiiu.set('4643','Comercio al por mayor de calzado');
    codCiiu.set('4644','Comercio al por mayor de aparatos y equipo de uso doméstico');
    codCiiu.set('4645','Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador');
    codCiiu.set('4649','Comercio al por mayor de otros utensilios domésticos n.c.p.');
    codCiiu.set('4651','Comercio al por mayor de computadores, equipo periférico y programas de informática');
    codCiiu.set('4652','Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones');
    codCiiu.set('4653','Comercio al por mayor de maquinaria y equipo agropecuarios');
    codCiiu.set('4659','Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.');
    codCiiu.set('4661','Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos');
    codCiiu.set('4662','Comercio al por mayor de metales y productos metalíferos');
    codCiiu.set('4663','Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción');
    codCiiu.set('4664','Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario');
    codCiiu.set('4665','Comercio al por mayor de desperdicios, desechos y chatarra');
    codCiiu.set('4669','Comercio al por mayor de otros productos n.c.p.');
    codCiiu.set('4690','Comercio al por mayor no especializado');
    codCiiu.set('4711','Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco');
    codCiiu.set('4719','Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco');
    codCiiu.set('4721','Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados');
    codCiiu.set('4722','Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados');
    codCiiu.set('4723','Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados');
    codCiiu.set('4724','Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados');
    codCiiu.set('4729','Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados');
    codCiiu.set('4731','Comercio al por menor de combustible para automotores');
    codCiiu.set('4732','Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores');
    codCiiu.set('4741','Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados');
    codCiiu.set('4742','Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados');
    codCiiu.set('4751','Comercio al por menor de productos textiles en establecimientos especializados');
    codCiiu.set('4752','Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados');
    codCiiu.set('4753','Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados');
    codCiiu.set('4754','Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación');
    codCiiu.set('4755','Comercio al por menor de artículos y utensilios de uso doméstico');
    codCiiu.set('4759','Comercio al por menor de otros artículos domésticos en establecimientos especializados');
    codCiiu.set('4761','Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados');
    codCiiu.set('4762','Comercio al por menor de artículos deportivos, en establecimientos especializados ');
    codCiiu.set('4769','Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados');
    codCiiu.set('4771','Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados');
    codCiiu.set('4772','Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.');
    codCiiu.set('4773','Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados');
    codCiiu.set('4774','Comercio al por menor de otros productos nuevos en establecimientos especializados');
    codCiiu.set('4775','Comercio al por menor de artículos de segunda mano');
    codCiiu.set('4781','Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles');
    codCiiu.set('4782','Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles');
    codCiiu.set('4789','Comercio al por menor de otros productos en puestos de venta móviles');
    codCiiu.set('4791','Comercio al por menor realizado a través de Internet');
    codCiiu.set('4792','Comercio al por menor realizado a través de casas de venta o por correo');
    codCiiu.set('4799','Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.');
    codCiiu.set('4911','Transporte férreo de pasajeros');
    codCiiu.set('4912','Transporte férreo de carga ');
    codCiiu.set('4921','Transporte de pasajeros');
    codCiiu.set('4922','Transporte mixto');
    codCiiu.set('4923','Transporte de carga por carretera');
    codCiiu.set('4930','Transporte por tuberías');
    codCiiu.set('5011','Transporte de pasajeros marítimo y de cabotaje ');
    codCiiu.set('5012','Transporte de carga marítimo y de cabotaje ');
    codCiiu.set('5021','Transporte fluvial de pasajeros');
    codCiiu.set('5022','Transporte fluvial de carga');
    codCiiu.set('5111','Transporte aéreo nacional de pasajeros ');
    codCiiu.set('5112','Transporte aéreo internacional de pasajeros ');
    codCiiu.set('5121','Transporte aéreo nacional de carga ');
    codCiiu.set('5122','Transporte aéreo internacional de carga ');
    codCiiu.set('5210','Almacenamiento y depósito');
    codCiiu.set('5221','Actividades de estaciones, vías y servicios complementarios para el transporte terrestre');
    codCiiu.set('5222','Actividades de puertos y servicios complementarios para el transporte acuático');
    codCiiu.set('5223','Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo');
    codCiiu.set('5224','Manipulación de carga');
    codCiiu.set('5229','Otras actividades complementarias al transporte');
    codCiiu.set('5310','Actividades postales nacionales');
    codCiiu.set('5320','Actividades de mensajería');
    codCiiu.set('5511','Alojamiento en hoteles ');
    codCiiu.set('5512','Alojamiento en apartahoteles');
    codCiiu.set('5513','Alojamiento en centros vacacionales ');
    codCiiu.set('5514','Alojamiento rural');
    codCiiu.set('5519','Otros tipos de alojamientos para visitantes');
    codCiiu.set('5520','Actividades de zonas de camping y parques para vehículos recreacionales');
    codCiiu.set('5530','Servicio por horas ');
    codCiiu.set('5590','Otros tipos de alojamiento n.c.p.');
    codCiiu.set('5611','Expendio a la mesa de comidas preparadas');
    codCiiu.set('5612','Expendio por autoservicio de comidas preparadas');
    codCiiu.set('5613','Expendio de comidas preparadas en cafeterías');
    codCiiu.set('5619','Otros tipos de expendio de comidas preparadas n.c.p.');
    codCiiu.set('5621','Catering para eventos');
    codCiiu.set('5629','Actividades de otros servicios de comidas');
    codCiiu.set('5630','Expendio de bebidas alcohólicas para el consumo dentro del establecimiento');
    codCiiu.set('5811','Edición de libros');
    codCiiu.set('5812','Edición de directorios y listas de correo');
    codCiiu.set('5813','Edición de periódicos, revistas y otras publicaciones periódicas');
    codCiiu.set('5819','Otros trabajos de edición');
    codCiiu.set('5820','Edición de programas de informática (software)');
    codCiiu.set('5911','Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión');
    codCiiu.set('5912','Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión');
    codCiiu.set('5913','Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión');
    codCiiu.set('5914','Actividades de exhibición de películas cinematográficas y videos');
    codCiiu.set('5920','Actividades de grabación de sonido y edición de musica');
    codCiiu.set('6010','Actividades de programación y transmisión en el servicio de radiodifusión sonora');
    codCiiu.set('6020','Actividades de programación y transmisión de televisión');
    codCiiu.set('6110','Actividades de telecomunicaciones alámbricas');
    codCiiu.set('6120','Actividades de telecomunicaciones inalámbricas');
    codCiiu.set('6130','Actividades de telecomunicación satelital');
    codCiiu.set('6190','Otras actividades de telecomunicaciones');
    codCiiu.set('6201','Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)');
    codCiiu.set('6202','Actividades de consultoría informática y actividades de administración de instalaciones informáticas');
    codCiiu.set('6209','Otras actividades de tecnologías de información y actividades de servicios informáticos');
    codCiiu.set('6311','Procesamiento de datos, alojamiento (hosting) y actividades relacionadas');
    codCiiu.set('6312','Portales web');
    codCiiu.set('6391','Actividades de agencias de noticias');
    codCiiu.set('6399','Otras actividades de servicio de información n.c.p.');
    codCiiu.set('6411','Banco Central');
    codCiiu.set('6412','Bancos comerciales');
    codCiiu.set('6421','Actividades de las corporaciones financieras');
    codCiiu.set('6422','Actividades de las compañías de financiamiento');
    codCiiu.set('6423','Banca de segundo piso');
    codCiiu.set('6424','Actividades de las cooperativas financieras');
    codCiiu.set('6431','Fideicomisos, fondos y entidades financieras similares');
    codCiiu.set('6432','Fondos de cesantías');
    codCiiu.set('6491','Leasing financiero (arrendamiento financiero)');
    codCiiu.set('6492','Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario');
    codCiiu.set('6493','Actividades de compra de cartera o factoring');
    codCiiu.set('6494','Otras actividades de distribución de fondos');
    codCiiu.set('6495','Instituciones especiales oficiales');
    codCiiu.set('6499','Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.');
    codCiiu.set('6511','Seguros generales ');
    codCiiu.set('6512','Seguros de vida');
    codCiiu.set('6513','Reaseguros');
    codCiiu.set('6514','Capitalización');
    codCiiu.set('6521','Servicios de seguros sociales de salud');
    codCiiu.set('6522','Servicios de seguros sociales de riesgos profesionales');
    codCiiu.set('6531','Régimen de prima media con prestación definida (RPM)');
    codCiiu.set('6532','Régimen de ahorro individual (RAI)');
    codCiiu.set('6611','Administración de mercados financieros');
    codCiiu.set('6612','Corretaje de valores y de contratos de productos básicos');
    codCiiu.set('6613','Otras actividades relacionadas con el mercado de valores');
    codCiiu.set('6614','Actividades de las casas de cambio');
    codCiiu.set('6615','Actividades de los profesionales de compra y venta de divisas');
    codCiiu.set('6619','Otras actividades auxiliares de las actividades de servicios financieros n.c.p.');
    codCiiu.set('6621','Actividades de agentes y corredores de seguros');
    codCiiu.set('6629','Evaluación de riesgos y daños, y otras actividades de servicios auxiliares');
    codCiiu.set('6630','Actividades de administración de fondos');
    codCiiu.set('6810','Actividades inmobiliarias realizadas con bienes propios o arrendados');
    codCiiu.set('6820','Actividades inmobiliarias realizadas a cambio de una retribución o por contrata ');
    codCiiu.set('6910','Actividades jurídicas');
    codCiiu.set('6920','Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria');
    codCiiu.set('7010','Actividades de administración empresarial');
    codCiiu.set('7020','Actividades de consultaría de gestión');
    codCiiu.set('7110','Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica');
    codCiiu.set('7120','Ensayos y análisis técnicos');
    codCiiu.set('7210','Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería ');
    codCiiu.set('7220','Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades');
    codCiiu.set('7310','Publicidad');
    codCiiu.set('7320','Estudios de mercado y realización de encuestas de opinión pública');
    codCiiu.set('7410','Actividades especializadas de diseño ');
    codCiiu.set('7420','Actividades de fotografía');
    codCiiu.set('7490','Otras actividades profesionales, cientéficas y técnicas n.c.p.');
    codCiiu.set('7500','Actividades veterinarias');
    codCiiu.set('7710','Alquiler y arrendamiento de vehículos automotores');
    codCiiu.set('7721','Alquiler y arrendamiento de equipo recreativo y deportivo');
    codCiiu.set('7722','Alquiler de videos y discos ');
    codCiiu.set('7729','Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.');
    codCiiu.set('7730','Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.');
    codCiiu.set('7740','Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor');
    codCiiu.set('7810','Actividades de agencias de empleo');
    codCiiu.set('7820','Actividades de agencias de empleo temporal');
    codCiiu.set('7830','Otras actividades de suministro de recurso humano');
    codCiiu.set('7911','Actividades de las agencias de viaje');
    codCiiu.set('7912','Actividades de operadores turísticos');
    codCiiu.set('7990','Otros servicios de reserva y actividades relacionadas');
    codCiiu.set('8010','Actividades de seguridad privada');
    codCiiu.set('8020','Actividades de servicios de sistemas de seguridad');
    codCiiu.set('8030','Actividades de detectives e investigadores privados');
    codCiiu.set('8110','Actividades combinadas de apoyo a instalaciones');
    codCiiu.set('8121','Limpieza general interior de edificios');
    codCiiu.set('8129','Otras actividades de limpieza de edificios e instalaciones industriales');
    codCiiu.set('8130','Actividades de paisajismo y servicios de mantenimiento conexos');
    codCiiu.set('8211','Actividades combinadas de servicios administrativos de oficina');
    codCiiu.set('8219','Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina');
    codCiiu.set('8220','Actividades de centros de llamadas (Call center)');
    codCiiu.set('8230','Organización de convenciones y eventos comerciales');
    codCiiu.set('8291','Actividades de agencias de cobranza y oficinas de calificación crediticia');
    codCiiu.set('8292','Actividades de envase y empaque');
    codCiiu.set('8299','Otras actividades de servicio de apoyo a las empresas n.c.p.');
    codCiiu.set('8411','Actividades legislativas de la administración pública');
    codCiiu.set('8412','Actividades ejecutivas de la administración pública');
    codCiiu.set('8413','Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social ');
    codCiiu.set('8414','Actividades reguladoras y facilitadoras de la actividad económica');
    codCiiu.set('8415','Actividades de los otros órganos de control');
    codCiiu.set('8421','Relaciones exteriores ');
    codCiiu.set('8422','Actividades de defensa');
    codCiiu.set('8423','Orden público y actividades de seguridad');
    codCiiu.set('8424','Administración de justicia');
    codCiiu.set('8430','Actividades de planes de seguridad social de afiliación obligatoria');
    codCiiu.set('8511','Educación de la primera infancia');
    codCiiu.set('8512','Educación preescolar');
    codCiiu.set('8513','Educación básica primaria');
    codCiiu.set('8521','Educación básica secundaria ');
    codCiiu.set('8522','Educación media académica');
    codCiiu.set('8523','Educación media técnica y de formación laboral');
    codCiiu.set('8530','Establecimientos que combinan diferentes niveles de educación ');
    codCiiu.set('8541','Educación técnica profesional');
    codCiiu.set('8542','Educación tecnológica');
    codCiiu.set('8543','Educación de instituciones universitarias o de escuelas tecnológicas');
    codCiiu.set('8544','Educación de universidades');
    codCiiu.set('8551','Formación académica no formal ');
    codCiiu.set('8552','Enseñanza deportiva y recreativa');
    codCiiu.set('8553','Enseñanza cultural');
    codCiiu.set('8559','Otros tipos de educación n.c.p.');
    codCiiu.set('8560','Actividades de apoyo a la educación');
    codCiiu.set('8610','Actividades de hospitales y clínicas, con internación');
    codCiiu.set('8621','Actividades de la práctica médica, sin internación');
    codCiiu.set('8622','Actividades de la práctica odontológica');
    codCiiu.set('8691','Actividades de apoyo diagnóstico');
    codCiiu.set('8692','Actividades de apoyo terapéutico');
    codCiiu.set('8699','Otras actividades de atención de la salud humana');
    codCiiu.set('8710','Actividades de atención residencial medicalizada de tipo general');
    codCiiu.set('8720','Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas');
    codCiiu.set('8730','Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas');
    codCiiu.set('8790','Otras actividades de atención en instituciones con alojamiento');
    codCiiu.set('8810','Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas');
    codCiiu.set('8890','Otras actividades de asistencia social sin alojamiento');
    codCiiu.set('9001','Creación literaria');
    codCiiu.set('9002','Creación musical');
    codCiiu.set('9003','Creación teatral');
    codCiiu.set('9004','Creación audiovisual');
    codCiiu.set('9005','Artes plásticas y visuales');
    codCiiu.set('9006','Actividades teatrales');
    codCiiu.set('9007','Actividades de espectáculos musicales en vivo');
    codCiiu.set('9008','Otras actividades de espectáculos en vivo');
    codCiiu.set('9101','Actividades de bibliotecas y archivos');
    codCiiu.set('9102','Actividades y funcionamiento de museos, conservación de edificios y sitios históricos');
    codCiiu.set('9103','Actividades de jardines botánicos, zoológicos y reservas naturales');
    codCiiu.set('9200','Actividades de juegos de azar y apuestas');
    codCiiu.set('9311','Gestión de instalaciones deportivas');
    codCiiu.set('9312','Actividades de clubes deportivos');
    codCiiu.set('9319','Otras actividades deportivas');
    codCiiu.set('9321','Actividades de parques de atracciones y parques temáticos');
    codCiiu.set('9329','Otras actividades recreativas y de esparcimiento n.c.p.');
    codCiiu.set('9411','Actividades de asociaciones empresariales y de empleadores');
    codCiiu.set('9412','Actividades de asociaciones profesionales');
    codCiiu.set('9420','Actividades de sindicatos de empleados');
    codCiiu.set('9491','Actividades de asociaciones religiosas');
    codCiiu.set('9492','Actividades de asociaciones políticas');
    codCiiu.set('9499','Actividades de otras asociaciones n.c.p.');
    codCiiu.set('9511','Mantenimiento y reparación de computadores y de equipo periférico');
    codCiiu.set('9512','Mantenimiento y reparación de equipos de comunicación');
    codCiiu.set('9521','Mantenimiento y reparación de aparatos electrónicos de consumo');
    codCiiu.set('9522','Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería ');
    codCiiu.set('9523','Reparación de calzado y artículos de cuero');
    codCiiu.set('9524','Reparación de muebles y accesorios para el hogar');
    codCiiu.set('9529','Mantenimiento y reparación de otros efectos personales y enseres domésticos');
    codCiiu.set('9601','Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel');
    codCiiu.set('9602','Peluquería y otros tratamientos de belleza');
    codCiiu.set('9603','Pompas fúnebres y actividades relacionadas');
    codCiiu.set('9609','Otras actividades de servicios personales n.c.p.');
    codCiiu.set('9700','Actividades de los hogares individuales como empleadores de personal doméstico');
    codCiiu.set('9810','Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio');
    codCiiu.set('9820','Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio');
    codCiiu.set('9900','Actividades de organizaciones y entidades extraterritoriales');

}
